### ISSUE TITLE
ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by mdstevens044** [NftEyez/sol-rayz#27]
Getting this error when trying to use sol-rayz 

`ReferenceError: TextEncoder is not defined
    at Object.<anonymous> (/home/runner/staked-particles-counter-bot/node_modules/@nfteyez/sol-rayz/src/utils.ts:23:32)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/ts-node-fm/src/index.ts:406:14)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/runner/staked-particles-counter-bot/node_modules/@nfteyez/sol-rayz/src/getParsedNftAccountsByOwner.ts:9:1)`

**Comment by mdstevens044** [comment]
No longer needed
